name: OpenOSRS - CI (PR)

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    name: PR title
    runs-on: ubuntu-latest

    steps:
      - name: PR title lint
        if: github.event_name == 'pull_request'
        uses: MorrisonCole/pr-lint-action@v1.6.1
        with:
          title-regex: '^([\w-/]+): \w+'
          on-failed-regex-fail-action: false
          on-failed-regex-request-changes: false
          on-failed-regex-create-review: true
          on-failed-regex-comment: "Your PR title should match the following regex: `%regex%`!"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  validate:
    name: Validate gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: gradle/wrapper-validation-action@v1.0.4

  build:
    name: Build
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Building plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: A1C-source

  test:
    name: Test
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Testing plugins
        run: ./gradlew test --stacktrace -x checkstyleMain --console=plain
        working-directory: A1C-source

  checkstyleMain:
    name: Checkstyle main
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Checking plugins code conventions (Main)
        run: ./gradlew checkstyleMain --console=plain
        working-directory: A1C-source

  checkstyleTest:
    name: Checkstyle test
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Checking plugins code conventions (Test)
        run: ./gradlew checkstyleTest --console=plain
        working-directory: A1C-source

  bump:
    name: Check version numbers
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - name: Extract actor repo
        shell: bash
        run: echo "##[set-output name=repo;]$(echo $(jq --raw-output .pull_request.head.repo.full_name "$GITHUB_EVENT_PATH"))"
        id: extract_actor_repo

      - name: Extract actor repo branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo $(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH"))"
        id: extract_actor_repo_branch

      - id: changedFiles
        name: Changed files exporter
        uses: futuratrepadeira/changed-files@v3.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Bump version numbers
        id: bumpNewChanged
        if: steps.changedFiles.outputs.files_created != '' && steps.changedFiles.outputs.files_updated != ''
        run: |
          ./gradlew bumpVersion --newFiles="${{ steps.changedFiles.outputs.files_created }}" --changedFiles="${{ steps.changedFiles.outputs.files_updated }}" --console=plain
        working-directory: A1C-source

      - name: Bump version numbers
        id: bumpChanged
        if: steps.changedFiles.outputs.files_created == '' && steps.changedFiles.outputs.files_updated != ''
        run: |
          ./gradlew bumpVersion --changedFiles="${{ steps.changedFiles.outputs.files_updated }}" --console=plain
        working-directory: A1C-source

      - name: Bump version numbers
        id: bumpNew
        if: steps.changedFiles.outputs.files_created != '' && steps.changedFiles.outputs.files_updated == ''
        run: |
          ./gradlew bumpVersion --newFiles="${{ steps.changedFiles.outputs.files_created }}" --console=plain
        working-directory: A1C-source

      - name: Detect changes
        id: detectChanges
        run: |
          git update-index --skip-worktree gradlew

          if ! git diff-index --quiet HEAD --; then
              git diff-index --name-only HEAD --

              exit 1
          fi
        working-directory: A1C-source

  approve:
    name: Approve
    needs: [build, test, checkstyleMain, checkstyleTest, bump]
    runs-on: ubuntu-latest

    steps:
      - name: Approve pull request
        if: github.event_name == 'pull_request' && github.actor == 'HeyImAdame'
        uses: hmarr/auto-approve-action@v2.2.1
        with:
          github-token: ${{ secrets.HeyImAdame }}
