name: OpenOSRS - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Building plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: A1C-source

  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Testing plugins
        run: ./gradlew test --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: A1C-source

  checkstyleMain:
    runs-on: ubuntu-latest
    name: Checkstyle main

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Checking plugins code conventions (Main)
        run: ./gradlew checkstyleMain --console=plain
        working-directory: A1C-source

  checkstyleTest:
    runs-on: ubuntu-latest
    name: Checkstyle test

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Checking plugins code conventions (Test)
        run: ./gradlew checkstyleTest --console=plain
        working-directory: A1C-source

  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bootstrap:
    runs-on: ubuntu-latest
    needs: [build, test, checkstyleMain, checkstyleTest]
    name: Bootstrap

    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: OpenOSRS

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: OpenOSRS

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: OpenOSRS

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: A1C-source

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain
        working-directory: A1C-source

      - name: Building plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: A1C-source

      - name: Bootstrapping plugins
        run: ./gradlew bootstrapPlugins --stacktrace --console=plain
        working-directory: A1C-source

      - uses: actions/checkout@v2.4.2
        with:
          repository: HeyImAdame/A1C
          ref: master
          path: A1C
          token: ${{ secrets.HeyImAdame }}

      - name: Copy bootstrap
        run: cp -af /home/runner/work/A1C-source/A1C-source/A1C-source/build/bootstrap/. /home/runner/work/A1C-source/A1C-source/A1C
        working-directory: A1C

      - name: Commit bootstrap
        run: |
          git add .
          git diff-index --quiet HEAD \
          || git -c user.name="GitHub" -c user.email="noreply@github.com" commit \
            --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
            -m "Automatic plugin bootstrap"
        working-directory: A1C

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.HeyImAdame }}
          directory: /home/runner/work/A1C-source/A1C-source/A1C
          repository: HeyImAdame/A1C
