name: A1C - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/checkout@v1

      - uses: actions/checkout@v1
        with:
          repository: open-osrs/runelite
          ref: master

      - uses: actions/checkout@v1
        with:
          repository: open-osrs/plugins
          ref: master

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/A1C-source/runelite

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: /home/runner/work/A1C-source/runelite

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/A1C-source/runelite

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal :runescape-api:publishToMavenLocal :injection-annotations:publishToMavenLocal --console=plain
        working-directory: /home/runner/work/A1C-source/runelite

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/A1C-source/plugins

      - name: Assembling plugins
        run: ./gradlew --console=plain
        working-directory: /home/runner/work/A1C-source/plugins

      - name: Building plugins
        run: ./gradlew -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/A1C-source/plugins

      - name: Upload plugins artifacts to local maven
        run: ./gradlew --console=plain
        working-directory: /home/runner/work/A1C-source/plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain

  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest

    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bootstrap:
    runs-on: ubuntu-latest
    needs: [build]
    name: Bootstrap

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/checkout@v1

      - uses: actions/checkout@v1
        with:
          repository: open-osrs/runelite
          ref: master

      - uses: actions/checkout@v1
        with:
          repository: open-osrs/plugins
          ref: master

      - uses: actions/checkout@v1
        with:
          repository: HeyImAdame/A1C
          ref: master

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/A1C-source/runelite

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: /home/runner/work/A1C-source/runelite

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/A1C-source/runelite

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal :runescape-api:publishToMavenLocal :injection-annotations:publishToMavenLocal --console=plain
        working-directory: /home/runner/work/A1C-source/runelite

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/A1C-source/plugins

      - name: Assembling plugins
        run: ./gradlew --console=plain
        working-directory: /home/runner/work/A1C-source/plugins

      - name: Building plugins
        run: ./gradlew --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/A1C-source/plugins

      - name: Upload plugins artifacts to local maven
        run: ./gradlew --console=plain
        working-directory: /home/runner/work/A1C-source/plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain

      - name: Bootstrapping plugins
        run: ./gradlew bootstrapPlugins --stacktrace --console=plain

      - name: Copy bootstrap
        run: cp -af /home/runner/work/A1C-source/A1C-source/build/bootstrap/. /home/runner/work/A1C-source/A1C/

      - name: Commit bootstrap
        run: |
          git add $(git ls-files -o --exclude-standard) plugins.json
          git diff-index --quiet HEAD \
          || git -c user.name="HeyImAdame" -c user.email="" commit \
            --author="HeyImAdame" \
            -m "Automatic plugin bootstrap"
        working-directory: /home/runner/work/A1C-source/A1C

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.HEYIMADAME }}
          directory: /home/runner/work/A1C-source/A1C
          repository: HeyImAdame/A1C
          branch: master
          force: true
